version: '3.8'


services:
  cache-node-1:
    build: ./cache-service
    ports:
      - "5001:8080"
    networks:
      - cache-net

  cache-node-2:
    build: ./cache-service
    ports:
      - "5002:8080"
    networks:
      - cache-net

  cache-node-3:
    build: ./cache-service
    ports:
      - "5003:8080"
    networks:
      - cache-net


networks:
  cache-net:
